### ISSUE TITLE
Lime branch, Demo server not responding  LIVE WEB DEMO AT: http://35.227.39.159:5050/ does not respond

### ISSUE THREAD

**Issue by jkent42** [priyamtejaswin/devise-keras#36]
LIVE WEB DEMO AT: http://35.227.39.159:5050/ times out

**Comment by jkent42** [comment]
![cantgetthere](https://user-images.githubusercontent.com/47161065/51944899-2796ed00-23eb-11e9-93b0-2dfec576f523.png)

**Comment by jkent42** [comment]
alternate address  needed ?

**Comment by priyamtejaswin** [comment]
hey!
we were hosting this on free GCP credits and they must have run out :)
it's unlikely that we'll have an alternate address/host again - i'll make sure to update the README file and remove the link.
